GET http://localhost:5000/skills
###
POST http://localhost:5000/user HTTP/1.1
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

{
    "email": "sas@eaczxsaample.com",
    "password": "stâscring",
    "phone": "stringstri",
    "fullname": "string"
}
###
POST http://localhost:5000/auth/login HTTP/1.1
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

{
    "email": "sas@eaczxample.com",
    "password" : "stâscring"
}
###

GET http://localhost:5000/homepage
Content-Type: text/html
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpYXQiOjE2NjE5MTQ5MDQsImV4cCI6MTY2MTkxNDkzNH0.slYK3rzeuROJsjWDtnJURsmQBoupMeIAxNZ8tjLvv7s

### 
POST http://localhost:5000/refreshToken HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMxYWI2ZDY3NjkwOTZjNDcwYjI1MmU1IiwiZW1haWwiOiJzYXNAZWFjenhhbXBsZS5jb20iLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNjYyNzk2NTcwLCJleHAiOjE2NjI4Mjk0MTJ9.GlYHudcHhkBB7d43JCrSsT6sFh4VFKcuoPyr6BkOtLo"
}
###
GET http://localhost:5000/users

###
POST  http://localhost:5000/services
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMxYWI2ZDY3NjkwOTZjNDcwYjI1MmU1IiwiZW1haWwiOiJzYXNAZWFjenhhbXBsZS5jb20iLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNjYyNzk2NTcwLCJleHAiOjE2NjI4Mjk0MTJ9.GlYHudcHhkBB7d43JCrSsT6sFh4VFKcuoPyr6BkOtLo

{
  "name": "Driver sssinstall",
  "category": [
    "628d9a48d0f5186097da588f"
  ],
  "skill": [
    "628d9e66cdb8ee9c670150a0"
  ],
  "providing_method": ["string"],
  "finish_estimated_time": 11,
  "status":2,
  "description": "string",
  "lower_bound_fee": 11,
  "upper_bound_fee": 13,
  "image": [
    "string"
  ],
  "type": "service",
  "expiration_time": "2021-04-06T22:13:19.776+00:00",
  "create_time": "2021-04-06T22:13:19.776+00:00"
}
###
GET http://localhost:5000/services/others/detail/631c7929cec6ad197135df4e
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMxYWI2ZDY3NjkwOTZjNDcwYjI1MmU1IiwiZW1haWwiOiJzYXNAZWFjenhhbXBsZS5jb20iLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNjYyNzk2NTcwLCJleHAiOjE2NjI4Mjk0MTJ9.GlYHudcHhkBB7d43JCrSsT6sFh4VFKcuoPyr6BkOtLo