GET http://localhost:5000/skills
###
POST http://localhost:5000/jobs HTTP/1.1
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMxZGFmOTEzZTlhNWU3YzQ3OWQ5ZGMzIiwiZW1haWwiOiJsYWxhbGEiLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNjYzNTUzMTU1LCJleHAiOjE2NjM1ODU5OTd9.ynEiFCF7C9F_0kG7prL07GraBhCIRielaXKhm9URydI

{
  "name": "string",
  "category": [
    "8faDbd2e9d006eEf9d84d531"
  ],
  "skill": [
    "8faDbd2e9d006eEf9d84d531"
  ],
  "description": "string",
  "providing_method": "string",
  "finish_estimated_time": "10",
  "lower_bound_fee": "12",
  "upper_bound_fee": "14",
  "image": [
    "string"
  ],
  "payment_method": "pay-per-hour",
  "required_level": "string",
  "expiration_time": "1970-01-01T00:00:00.011+00:00"
}
###
POST http://localhost:5000/user HTTP/1.1
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

{
    "email": "quangthinh0101@gmail.com",
    "password": "hihihi",
    "phone": "stringstri",
    "fullname": "string"
}
###
GET http://localhost:5000/services/myService
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjI1NTMyMjYyNWE3ZmVhY2UwNjJmYzRiIiwiZW1haWwiOiJyb2NrZXRtZTE0M0BnbWFpbC5jb20iLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNjY0MTk5NjgwLCJleHAiOjE2NjQyMzI1MjJ9.EyEvgF6jjay8El3aePGHhXLbZVapgic6w_gKv_KoR48


###
PATCH  http://localhost:5000/services/approve/631c7929cec6ad197135df4e HTTP/1.1
Content-Type: application/json
###
GET http://localhost:5000/offers/62fc59b6f23abda15c2cd45f?limit=20&page=1&sortBy=create_time
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJhNDcyZmMwYzI2M2EwN2VkZTlhOTU3IiwiZW1haWwiOiJoYXN1bGUuZGVsbEBnbWFpbC5jb20iLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNjY0MzQ2MzAyLCJleHAiOjE2NjQzNzkxNDR9.wXVaXkakXUhyilYcKTLkKh_XH--aiHBL4buqUxZdzls
###

