GET http://localhost:5000/skills
###
POST http://localhost:5000/jobs HTTP/1.1
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMxZGFmOTEzZTlhNWU3YzQ3OWQ5ZGMzIiwiZW1haWwiOiJsYWxhbGEiLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNjYzNTUzMTU1LCJleHAiOjE2NjM1ODU5OTd9.ynEiFCF7C9F_0kG7prL07GraBhCIRielaXKhm9URydI

{
  "name": "string",
  "category": [
    "8faDbd2e9d006eEf9d84d531"
  ],
  "skill": [
    "8faDbd2e9d006eEf9d84d531"
  ],
  "description": "string",
  "providing_method": "string",
  "finish_estimated_time": "10",
  "lower_bound_fee": "12",
  "upper_bound_fee": "14",
  "image": [
    "string"
  ],
  "payment_method": "pay-per-hour",
  "required_level": "string",
  "expiration_time": "1970-01-01T00:00:00.011+00:00"
}
###
POST http://localhost:5000/user HTTP/1.1
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

{
    "email": "kakakaka",
    "password": "kakakaka",
    "phone": "stringstri",
    "fullname": "string"
}
###
POST http://localhost:5000/auth/login HTTP/1.1
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

{
    "email": "kakakaka",
    "password" : "kakakaka"
}
###
PATCH  http://localhost:5000/services/approve/631c7929cec6ad197135df4e HTTP/1.1
Content-Type: application/json
###
GET http://localhost:5000/offers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMxZGFmOTEzZTlhNWU3YzQ3OWQ5ZGMzIiwiZW1haWwiOiJsYWxhbGEiLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNjYzNTU2MzE1LCJleHAiOjE2NjM1ODkxNTd9.u0ZwCJV-xjzClDU517pv8m2fdE7R1srpXuGIvEJMg28
###


POST  http://localhost:5000/offers/6327f1f4dcd794e6a073f5b3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMyM2ZlNGE5NTgwMzVkZTI0MzNmYmMxIiwiZW1haWwiOiJrYWtha2EiLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNjYzNTYyMzA2LCJleHAiOjE2NjM1OTUxNDh9.cB0xEHsGc0U6hhDgpQLK0ApfZw9TV_sl0lOUHBKwtwo

{
  "offer_price": 24,
  "offer_finish_estimated_time": 12,
  "introduction": "intrssoduction"
}
###
POST http://localhost:5000/order/acceptOffer/6327f253dcd794e6a073f5ba
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMxZGFmOTEzZTlhNWU3YzQ3OWQ5ZGMzIiwiZW1haWwiOiJsYWxhbGEiLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNjYzNTUzMTU1LCJleHAiOjE2NjM1ODU5OTd9.ynEiFCF7C9F_0kG7prL07GraBhCIRielaXKhm9URydI

{
  "note":"lalala"
}
###
POST http://localhost:5000/offers/631db7f597a321c3249a789c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMxZGFmOTEzZTlhNWU3YzQ3OWQ5ZGMzIiwiZW1haWwiOiJsYWxhbGEiLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNjYzNTUzMTU1LCJleHAiOjE2NjM1ODU5OTd9.ynEiFCF7C9F_0kG7prL07GraBhCIRielaXKhm9URydI

{
  "offer_price":"100",
  "offer_finish_estimated_time": "10",
  "introduction":"lala"
} 
###
POST http://localhost:5000/order/complain/6327f33edcd794e6a073f5c0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMxZGFmOTEzZTlhNWU3YzQ3OWQ5ZGMzIiwiZW1haWwiOiJsYWxhbGEiLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNjYzNTUzMTU1LCJleHAiOjE2NjM1ODU5OTd9.ynEiFCF7C9F_0kG7prL07GraBhCIRielaXKhm9URydI

{
  "complain": "too bad"
}
###
GET http://localhost:5000/order/all?page=1&limit=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMyODQxODcxNGVhNDBmYWIyNDAyMWQ0IiwiZW1haWwiOiJrYWtha2FrYSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY2MzU4MjYzMiwiZXhwIjoxNjYzNjE1NDc0fQ.BCpOKpsDisUFJBgjKR23lju9GkLGzucrJOLb2zzRCyw
###
GET http://localhost:5000/order/6327f33edcd794e6a073f5c0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMyODQxODcxNGVhNDBmYWIyNDAyMWQ0IiwiZW1haWwiOiJrYWtha2FrYSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY2MzU4MjYzMiwiZXhwIjoxNjYzNjE1NDc0fQ.BCpOKpsDisUFJBgjKR23lju9GkLGzucrJOLb2zzRCyw

###
DELETE http://localhost:5000/admin_bank/delete/632a7ab0c076814b30018b3f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMyODQxODcxNGVhNDBmYWIyNDAyMWQ0IiwiZW1haWwiOiJrYWtha2FrYSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY2MzcyODE5MiwiZXhwIjoxNjYzNzYxMDM0fQ.9wcd58Ycb6rsvSlA-1mRKpuF9PTaU_vmshDXsJ0FI6w

